name: Deploy API to Self-Hosted Server (Develop)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Prepare and update codebase
        run: |
          cd /opt/slack-rcti
          git stash --include-untracked || true
          git checkout development
          git pull origin development

      - name: Install Python dependencies
        run: |
          cd /opt/slack-rcti
          pip install -r requirements.txt

      - name: Stop existing process
        run: |
          cd /opt/slack-rcti
          pkill -f "python src/app.py" || true

      - name: Start API server in background
        run: |
          cd /opt/slack-rcti
          nohup python src/app.py > bot.log 2>&1 &
          echo "API started in background"

      - name: Stop existing background process
        run: |
          cd /opt/slack-rcti
          tmux kill-session -t slack-rcti || true
          echo "Previous tmux session terminated (if existed)"

      - name: Start API in tmux
        run: |
          cd /opt/slack-rcti
          tmux new-session -d -s slack-rcti "python src/app.py > bot.log 2>&1"
          echo "API started in tmux session: slack-rcti"

      - name: Check if API is running
        run: |
          sleep 5
          if tmux has-session -t slack-rcti 2>/dev/null; then
            echo "API is running successfully in tmux session"
          else
            echo "Failed to start API in tmux"
            exit 1
          fi

      - name: Notify via Telegram
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
        run: |
          cd /opt/slack-rcti
          set -a
          if [ -f .env ]; then
            source .env
          fi
          set +a

          GIT_INFO=$(git log -1 --pretty=format:"%s|%h|%an|%ar")
          LAST_COMMIT_MSG=$(echo "$GIT_INFO" | cut -d'|' -f1 | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g')
          LAST_COMMIT_HASH=$(echo "$GIT_INFO" | cut -d'|' -f2)
          LAST_COMMIT_AUTHOR=$(echo "$GIT_INFO" | cut -d'|' -f3 | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g')
          LAST_COMMIT_TIME=$(echo "$GIT_INFO" | cut -d'|' -f4)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g')

          TELEGRAM_API="https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
          MSG="✨ AlyaBot Deploy Sukses (Develop)! ✨%0A%0ABranch: <code>$BRANCH_NAME</code>%0ACommit: <code>$LAST_COMMIT_HASH</code>%0AAuthor: <b>$LAST_COMMIT_AUTHOR</b>%0ATime: $LAST_COMMIT_TIME%0A%0A<b>Changelog:</b>%0A$LAST_COMMIT_MSG"

          if [ -n "$TELEGRAM_BOT_TOKEN" ] && [ -n "$TELEGRAM_CHAT_ID" ]; then
            if [ -n "$TELEGRAM_TOPIC_ID" ]; then
              curl -s -X POST "$TELEGRAM_API" \
                -d chat_id="$TELEGRAM_CHAT_ID" \
                -d message_thread_id="$TELEGRAM_TOPIC_ID" \
                -d text="$MSG" \
                -d parse_mode="HTML" > /dev/null 2>&1 || true
            else
              curl -s -X POST "$TELEGRAM_API" \
                -d chat_id="$TELEGRAM_CHAT_ID" \
                -d text="$MSG" \
                -d parse_mode="HTML" > /dev/null 2>&1 || true
            fi
            echo "Deployment notification sent to Telegram"
          else
            echo "TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not set, skip Telegram notification"
          fi